config/routes.rb
LyndaSqlite::Application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'admin/menu'
  get 'public/albums'

  resources :users
  resources :carts
  resources :customers
  resources :orders
  resources :features
  resources :artists
  resources :albums
  resources :line_items

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :artist
	has_many :line_items
	has_many :features_assignments
	has_many :features, through: :features_assignments
	validates :title, :description, :published_date, :genre, :artist_id, :price, :image_path, :presence => true

	before_destroy :ensure_not_referenced_by_any_line_item

	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors.add(:base, 'Cannot delete. This product is currently in a line item')
			return false
		end

	end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	validates :name, :biography, :birthdate, :presence => true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_album(album_id, price)
		current_item = line_items.where(album_id: album_id).first
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(album_id: album_id, price: price)
		end
		return current_item
	end

	def total_price
		line_items.to_a.sum { |line_item| line_item.total_price }
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
	validates :name, :lastname, :email, presence: true
	validates :email, uniqueness: true
end

app/models/feature.rb
class Feature < ActiveRecord::Base
	has_many :features_assignments
	has_many :albums, through: :features_assignments
	validates :name, presence: true
end

app/models/features_assignment.rb
class FeaturesAssignment < ActiveRecord::Base
	belongs_to :album
	belongs_to :feature
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :album
	belongs_to :order
	belongs_to :cart

	def total_price
		price * quantity
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	belongs_to :customer

	validates :invoice_number, :customer_id, presence: true

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
	after_destroy :ensure_an_admin_remains

	# check that the username is present and unique
	validates :username, presence: true, uniqueness: true

	# validates that the password and confirm password fields match
	validates :password_confirmation, presence: true
	validates :password, confirmation: true

	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(username, password)
		logger.info("--> username: #{username} password: #{password}")
		if user = find_by_username(username)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	# 'password' is a virtual attribute
	def password=(password)
		logger.info("--> went here")
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end
	end

	private
	def password_must_be_present
		errors.add(:password, "can't be empty" ) unless hashed_password.present?
	end
	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end

	def ensure_an_admin_remains
		if User.count.zero?
			raise "Can't delete last user"
		end
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: [:show, :create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to public_albums_url, notice: 'Your cart is empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error("Attempt to access invalid cart #{params[:id]}")
      redirect_to public_albums_url, notice: 'Invalid cart'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice" ><%= notice %></p>
<% end %>
<h1>Your cart</h1>
<%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: 'Are you sure you?'} %>

<table>
  <thead>
    <tr>
    	<th></th>
      <th>Album</th>
      <th>Artist</th>
      <th>Unit Price</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.line_items.each do |line_item| %>
      <tr>
      	<td><%= image_tag line_item.album.image_path, size: '30x30' %></td>
        <td><%= line_item.album.title %></td>
        <td><%= line_item.album.artist.name %></td>
        <td><%= line_item.price %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.total_price %></td>
        <td><%= link_to 'Remove Item', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      <tr>
        <td colspan="5">SubTotal :</td>
        <td><strong><%= number_to_currency(@cart.total_price) %></strong></td>
        <td><%= button_to 'Checkout', new_order_path, method: :get %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'Buy more albums', public_albums_path %>