config/routes.rb
LyndaSqlite::Application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'admin/menu'
  get 'public/albums'

  resources :users
  resources :carts
  resources :customers
  resources :orders
  resources :features
  resources :artists
  resources :albums
  resources :line_items

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :artist
	has_many :line_items
	has_many :features_assignments
	has_many :features, through: :features_assignments
	validates :title, :description, :published_date, :genre, :artist_id, :price, :image_path, :presence => true

	before_destroy :ensure_not_referenced_by_any_line_item

	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors.add(:base, 'Cannot delete. This product is currently in a line item')
			return false
		end

	end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	validates :name, :biography, :birthdate, :presence => true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_album(album_id, price)
		current_item = line_items.where(album_id: album_id).first
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(album_id: album_id, price: price)
		end
		return current_item
	end

	def total_price
		line_items.to_a.sum { |line_item| line_item.total_price }
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
	validates :name, :lastname, :email, presence: true
	validates :email, uniqueness: true
end

app/models/feature.rb
class Feature < ActiveRecord::Base
	has_many :features_assignments
	has_many :albums, through: :features_assignments
	validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :album
	belongs_to :order
	belongs_to :cart

	def total_price
		price * quantity
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	belongs_to :customer

	validates :invoice_number, :customer_id, presence: true

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
	after_destroy :ensure_an_admin_remains

	# check that the username is present and unique
	validates :username, presence: true, uniqueness: true

	# validates that the password and confirm password fields match
	validates :password_confirmation, presence: true
	validates :password, confirmation: true

	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(username, password)
		logger.info("--> username: #{username} password: #{password}")
		if user = find_by_username(username)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	# 'password' is a virtual attribute
	def password=(password)
		logger.info("--> went here")
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end
	end

	private
	def password_must_be_present
		errors.add(:password, "can't be empty" ) unless hashed_password.present?
	end
	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end

	def ensure_an_admin_remains
		if User.count.zero?
			raise "Can't delete last user"
		end
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/menu.html.erb
<div class="menu">
	<ul>
		<% links = %w(albums artists features orders customers) %>
		<% for link in links %>
			<li><%= link_to link.upcase, :controller => link, :action => 'index' %></li>
		<% end %>
	</ul>
</div>

app/views/layouts/albums.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LyndaSqlite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Public Albums', public_albums_path %> |
<%= link_to 'My Cart', cart_path(session[:cart_id] || 4) %> |
<%= link_to 'Log In', login_url %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LyndaSqlite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Albums', albums_path %> |
<%= link_to 'Public Albums', public_albums_path %> |
<%= link_to 'Artists', artists_path %> |
<%= link_to 'Features', features_path %> |
<%= link_to 'Orders', orders_path %> |
<%= link_to 'Customers', customers_path %> |
<%= link_to 'Line Items', line_items_path %> |
<%= link_to 'My Cart', cart_path(session[:cart_id] || 4) %> |
<%= button_to 'Logout', logout_path, method: :delete %>
<%= yield %>

</body>
</html>